development:
  adapter: postgresql
  database: wessexccp_development
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
test:
  adapter: postgresql
  database: wessexccp_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wessexccp_production
  pool: 5
  timeout: 5000
